package com.company.bookservice.controller;

import com.company.bookservice.exception.NotFoundException;
import com.company.bookservice.model.Book;
import com.company.bookservice.model.BookViewModel;
import com.company.bookservice.model.Note;
import com.company.bookservice.service.BookService;
import com.company.bookservice.util.NoteServiceClient;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestTemplate;

import javax.validation.Valid;
import java.util.List;

@RestController
@RequestMapping(value = "/books")
@RefreshScope
public class BookController {

    @Autowired
    BookService service;

    @Autowired
    private final NoteServiceClient noteServiceClient;

    public BookController(NoteServiceClient noteServiceClient) {
        this.noteServiceClient = noteServiceClient;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public BookViewModel saveBook(@RequestBody @Valid BookViewModel bookViewModel) {

        return service.saveBook(bookViewModel);
    }

//    Create Book
//===========
//    URI: /books
//    HTTP Method: POST
//    RequestBody: Book data (minus ID)
//    ResponseBody: Book data (plus autogenerated ID)
//

    @GetMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public BookViewModel findBookById(@PathVariable("id") int id) {
        System.out.println(service);
        BookViewModel bookViewModel = service.findBookById(id);
        if (bookViewModel == null) {
            throw new NotFoundException("Book cannot be retrieved by ID provided: " + id);
        }
        return bookViewModel;
    }
 //    Get Book
//========
//    URI: /books/{id}
//    HTTP Method: GET
//    RequestBody: None
//    ResponseBody: Book data
//
    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public List<BookViewModel> findAllBooks() {
        System.out.println(service);
        return service.findAllBooks();
    }
//    Get All Books
//=============
//    URI: /books
//    HTTP Method: GET
//    RequestBody: None
//    ResponseBody: Array of Book data
//
    @PutMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public void updateBook(@PathVariable("id") int id, @RequestBody @Valid BookViewModel bookViewModel) {
        System.out.println(service);
        if (bookViewModel.getBookId() == 0) {
            bookViewModel.setBookId(id);
        }
        if (id != bookViewModel.getBookId()) {
            throw new IllegalArgumentException("Book ID on path must match ID of Book.");
        }
        service.updateBook(bookViewModel);
    }

//    Update Book
//===========
//    URI: /books/{id}
//    HTTP Method: PUT
//    RequestBody: Book data
//    ResponseBody: None
//

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void deleteBook(@PathVariable ("id") int id) {

        service.deleteBook(id);
    }
//    Delete Book
//===========
//    URI: /books/{id}
//    HTTP Method: DELETE
//    RequestBody: None
//    ResponseBody: None
}
